# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [32]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [33]:
# Import torch
import torch

# Create random tensor
random_tensor_one = torch.rand(7,7)
print(random_tensor_one)
print(random_tensor_one.shape)
############
random_tensor_two = torch.rand(size=(7,7))
print(random_tensor_two)
print(random_tensor_two.shape)

tensor([[0.8259, 0.2218, 0.6009, 0.3572, 0.0663, 0.1744, 0.7042],
        [0.6979, 0.1908, 0.3441, 0.0326, 0.7688, 0.9323, 0.6635],
        [0.1906, 0.7637, 0.9149, 0.3977, 0.4180, 0.6731, 0.5643],
        [0.3347, 0.0358, 0.1494, 0.5271, 0.4732, 0.9129, 0.5171],
        [0.3713, 0.0115, 0.0403, 0.7077, 0.9454, 0.4924, 0.0531],
        [0.6775, 0.9072, 0.1691, 0.3684, 0.5421, 0.2149, 0.0364],
        [0.7189, 0.0897, 0.3745, 0.2345, 0.8760, 0.5965, 0.7319]])
torch.Size([7, 7])
tensor([[0.1614, 0.9214, 0.5446, 0.2227, 0.4673, 0.1460, 0.4769],
        [0.7792, 0.2752, 0.9226, 0.6527, 0.4125, 0.6562, 0.4079],
        [0.3838, 0.1720, 0.7913, 0.8001, 0.6712, 0.7957, 0.9995],
        [0.9708, 0.0175, 0.6140, 0.4572, 0.6698, 0.4030, 0.6396],
        [0.0400, 0.7285, 0.9804, 0.4101, 0.1023, 0.0844, 0.4041],
        [0.4924, 0.5558, 0.5627, 0.8766, 0.4093, 0.6427, 0.2343],
        [0.9918, 0.6919, 0.4307, 0.8287, 0.6770, 0.5857, 0.3524]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [34]:
# Create another random tensor
randomTensor = torch.rand(1,7)
resultOne = torch.matmul(random_tensor_one, randomTensor.T)
resultTwo  = torch.mm(random_tensor_one, randomTensor.T)
resultThree = random_tensor_one @ randomTensor.T
###########
randomTensorTwo = torch.rand(1,7).T
resultFour = torch.matmul(random_tensor_one, randomTensorTwo)
# Perform matrix multiplication
print(resultOne)
print(resultTwo)
print(resultThree)
print(resultFour)

tensor([[1.3808],
        [1.6325],
        [1.6328],
        [1.2851],
        [1.2900],
        [1.4848],
        [1.7360]])
tensor([[1.3808],
        [1.6325],
        [1.6328],
        [1.2851],
        [1.2900],
        [1.4848],
        [1.7360]])
tensor([[1.3808],
        [1.6325],
        [1.6328],
        [1.2851],
        [1.2900],
        [1.4848],
        [1.7360]])
tensor([[1.3055],
        [2.1796],
        [1.6908],
        [1.7198],
        [1.2356],
        [0.9161],
        [2.0657]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [35]:
# Set manual seed
import random
random_seed = 0
torch.manual_seed(random_seed)
# Create two random tensors
ran1Tensor = torch.rand(7,7)
ran2Tensor = torch.rand(1,7).T
# Matrix multiply tensors
result = torch.mm(ran1Tensor, ran2Tensor)
print(f'{result}, {result.shape}')

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]), torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [36]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [37]:
# Set random seed
randseed = torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'Device: {device}')
# Create two random tensors on GPU
randOne = torch.rand(2,3)
randTwo = torch.rand(2,3)
randOne_gpu = randOne.to(device)
randTwo_gpu = randTwo.to(device)
print(randOne_gpu)
print(randTwo_gpu)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [38]:
# Perform matmul on tensor_A and tensor_B
mat_mul= torch.matmul(randOne_gpu, randTwo_gpu.T)
print(f'{mat_mul}, {mat_mul.shape}')


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [39]:
# Find max
maximum_value = mat_mul.max()
print(f'Maximum value is: {maximum_value}')
max_val = torch.max(mat_mul)
print(f'Max: {max_val}')
# Find min
minimum_value = mat_mul.min()
print(f'Minimum value is:{minimum_value}')
min_val = torch.min(mat_mul)
print(f'Min: {min_val}')

Maximum value is: 0.5617256760597229
Max: 0.5617256760597229
Minimum value is:0.3647301495075226
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [40]:
# Find arg max
print(f'Max index: {mat_mul.argmax()}')
# Find arg min
print(f'Min index: {mat_mul.argmin()}')

Max index: 3
Min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
ran_seed = torch.manual_seed(7)

# Create random tensor
final_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
newShapedTensor = final_tensor.squeeze()

# Print out tensors and their shapes
print(final_tensor, final_tensor.shape)
print(newShapedTensor, newShapedTensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
